spring:
  application:
    name: event-sourcing-config
  cloud:
    config:
      server: 
        git:
          uri: file://C:/Arun/TFG/demo/event-sourcing-demo/event-sourcing-config/com/event/sourcing/config/files   

server:
  port: 8888

