spring:
  application:
    name: event-sourcing-order
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
      
event:
  sourcing:
    amqp:
      rabbit:
        queue: order-event-queue
        exchange: order-exchange
 
server:
  port: 8085
